name: Java Tests

on:
  push:
    branches:
      - main

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight U

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #setup java jdk21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21-ea
          distribution: temurin 
    #create a maven cache package, this willd download any needed dependencies also
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests
        run: mvn -B test --file pom.xml