name: Java Tests

on:
  push: # Remove branch restriction
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

#      - name: Cache Maven packages
#        uses: actions/cache@v2
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#          restore-keys: ${{ runner.os }}-m2

      - name: Test with Maven
        run: mvn test --file pom.xml

      - name: Clean with Maven
        run: mvn clean --file pom.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml
