name: Java Tests

on:
  push: # Remove branch restriction.
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: maven

      - name: Display Java version
        run: java -version

      - name: Clean with Maven
        run: mvn clean --file pom.xml

      - name: Build with Maven
        run: mvn -Djava.awt.headless=true -B package --file pom.xml

      - name: Test with Maven
        run: mvn -Djava.awt.headless=true -B test --file pom.xml

      - name: List dependencies
        run: mvn dependency:tree --file pom.xml
