name: Building the project and creating a JAR file

on:
  push:
    branches:
      - master
      - main-dev
  pull_request:

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Maven project and create JAR
        run: |
          mvn -B package --file pom.xml -Dmaven.test.skip
          mkdir staging && cp target/*.jar staging

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19-ea
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn test

      - name: Clean with Maven
        run: mvn clean verify

      - name: Set up cache for Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Persist workflow data as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: github-actions-artifact
          path: staging

      - name: Upload code coverage report to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.credentials }}
          folderId: ${{ secrets.folderId }}
          name: "coverage-report.zip" #
          overwrite: "true" #
