name: "Building the project making a jar file"

on:
  push:
    branches:
      -master
      -'main-dev'
  pull_request:


  - name: "Build maven project"
    run: |
      mvn -B package --file pom.xml -Dmaven.test.skip
      mkdir staging && cp target/*.jar staging

  - name: Set up cache for Maven
    uses: actions/cache@v2
    with:
      path: ~/.m2
      key: ${{ runner.os }}-m2-${{ hasFiles('**/pom.xml') }}
      restore-keys: ${{ runner.os }}-m2

  - name: Persist workflow data as artifacts
    uses: actions/upload-artifact@v2
    with:
      name: github-actions-artifact
      path: staging

