name: Building the project and creating a JAR file

on:
  push:
    branches:
      - master
      - main-dev
  pull_request:

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: maven


      - name: Package the maven project
        run: mvn -B package --file pom.xml

      - name: Create executable Jar File
        run: mvn clean compile assembly:single

      - name: Run the created file
        run: java -jar jabberPointerAssigment/target/JabberPoint-1.0-SNAPSHOT-jar-with-dependencies.jar

      - name: Upload Jar to OneDrive
        uses: vekexasia/onedrive-upload-gh-action@v2.0.0
        env:

#      - name: Persist workflow data as artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: github-actions-artifact
#          path: staging
#
#      - name: Upload code coverage report to Google Drive
#        uses: adityak74/google-drive-upload-git-action@main
#        with:
#          credentials: ${{ secrets.credentials }}
#          folderId: ${{ secrets.folderId }}
#          name: "coverage-report.zip" #
#          overwrite: "true" #
