name: Building the project and creating a JAR file

on:
  push:
    branches:
      - master
      - main-dev

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Package the maven project
        run: mvn -B package --file pom.xml

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: target/MehdiBernardo-1.0-SNAPSHOT-jar-with-dependencies.jar

      - name: Upload Jar to Google
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCA_SA_KEY }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}


      - name: Deploy via GCS
        run: |
          gsutil -m rm -rf gs://github-jabber/* || echo "$?"
          gsutil -m cp -r target/MehdiBernardo-1.0-SNAPSHOT-jar-with-dependencies.jar  gs://github-jabber/
