name: Building the project and creating a JAR file

on:
  push:
    branches:
      - master
      - main-dev
  pull_request:

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: maven


      - name: Package the maven project
        run: mvn -B package --file pom.xml

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: target/MehdiBernardo-1.0-SNAPSHOT-jar-with-dependencies.jar

      - name: Upload Jar to Google
        uses: vekexasia/onedrive-upload-gh-action@v2.0.0
        with:
          service_account_key: ${{ secrets.GCA_SA_KEY }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}

      - name: Deploy via GCS
        run: | 
          gsustil -m rm -rf gs://github-jabber/*
          gsutil -m cp -r * gs://github-jabber/

#      - name: Persist workflow data as artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: github-actions-artifact
#          path: staging
#
#      - name: Upload code coverage report to Google Drive
#        uses: adityak74/google-drive-upload-git-action@main
#        with:
#          credentials: ${{ secrets.credentials }}
#          folderId: ${{ secrets.folderId }}
#          name: "coverage-report.zip" #
#          overwrite: "true" #
