#https://github.com/super-linter/super-linter
name: Lint

on:  # yamllint disable-line rule:truthy
  pull_request:
    path:
      -'src/**'

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout     code
        uses: actions/checkout@v2
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200
      - name: Build with dotnet
        run: dotnet build ./src/WebAppSSLManager.sln --configuration Release

      - name: Super-linter

        uses: super-linter/super-linter@v6.3.0  # x-release-please-version
        env:
          CREATE_LOG_FILE: true
          LOG_FILE: linger.log
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.BERNARDOMEHDISECRET }}


  verify-arm:

    runs-on: ubuntu-latest

    steps:
      - name: ARM Template Toolkit (ARM TTK)
        # You may pin to the exact commit or the version.
        # uses: aliencube/arm-ttk-actions@6fa8c0ad67d034f6e274d5276fb492f7d263ae4a
        uses: aliencube/arm-ttk-actions@v0.3
        with:
          # ARM Template file path to run the test. It can be either a directory or single file.
          path: ARM Template/