#https://github.com/super-linter/super-linter
name: Lint

on:  # yamllint disable-line rule:truthy
  pull_request:
    path:
      -'src/**'

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0


      - name: Super-linter
        uses: super-linter/super-linter@v6.3.0  # x-release-please-version
        env:
          CREATE_LOG_FILE: true
          LOG_FILE: linger.log
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.BERNARDOMEHDISECRET }}
          
      - name: Upload log file
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: super-linter-log
          path: ./super-linter.log

